// Vercel serverless function (Node.js runtime). Embeds the visitor's
// question with Gemini, retrieves the closest chunks from the
// pre-computed knowledge base (src/data/knowledgeEmbeddings.json,
// generated by scripts/generateEmbeddings.js) via cosine similarity, then
// asks Groq to answer grounded only in that retrieved context. Two
// providers on purpose: the stored embeddings were generated with Gemini
// in Phase 7a, so query embeddings must use the same model to be
// comparable, while generation moved to Groq for the larger free-tier
// quota. Stateless per request: nothing about the visitor or their
// question is logged or stored beyond the lifetime of the request.
import { GoogleGenAI } from '@google/genai'
import Groq from 'groq-sdk'
import knowledgeBase from '../src/data/knowledgeEmbeddings.json' with { type: 'json' }

export const config = {
  maxDuration: 20,
}

const EMBEDDING_MODEL = 'gemini-embedding-001'
const GENERATION_MODEL = 'openai/gpt-oss-120b'
const MAX_QUESTION_LENGTH = 500
const TOP_K = 4

const RATE_LIMIT_WINDOW_MS = 60_000
const RATE_LIMIT_MAX_REQUESTS = 10
// In-memory, per-function-instance rate limiter, keyed by IP. This resets
// on cold starts and isn't shared across concurrent instances — a basic
// deterrent against casual abuse, not a hard guarantee. A real guarantee
// would need an external store (e.g. Redis/Upstash), deliberately out of
// scope for a personal portfolio site.
const requestLog = new Map()

const SYSTEM_INSTRUCTION = `You are a helpful assistant on Chandra Sivakumar's personal portfolio website. You are not Chandra, you are an assistant who knows his background well and answers questions on his behalf, so a visitor can get a real sense of him without clicking through every page. Speak about Chandra in the third person.

If asked who you are or what you do, explain briefly: you're an AI assistant trained on Chandra's background (his experience, education, and projects), here to answer questions about him directly.

Answer only using the provided retrieved context chunks below. Do not use outside knowledge about Chandra or invent information not present in the context. If the retrieved context doesn't contain a relevant answer, say so plainly rather than guessing, e.g. 'I don't have information about that in what I know about Chandra, feel free to ask about his experience, education, projects, or background instead.' If the question is unrelated to Chandra entirely, politely decline and redirect, e.g. 'I'm just here to help you get to know Chandra, ask me about his experience, projects, or path into product management.' Keep answers concise and conversational, a few sentences, not an essay, unless the question genuinely requires more detail.

Write in plain conversational prose. Do not use markdown formatting, bullet points, or numbered lists — this is a chat interface that renders plain text.`

function getClientIp(request) {
  const forwarded = request.headers['x-forwarded-for']
  if (typeof forwarded === 'string' && forwarded.length > 0) {
    return forwarded.split(',')[0].trim()
  }
  return request.socket?.remoteAddress || 'unknown'
}

function isRateLimited(ip) {
  const now = Date.now()
  const recent = (requestLog.get(ip) || []).filter((t) => now - t < RATE_LIMIT_WINDOW_MS)
  recent.push(now)
  requestLog.set(ip, recent)
  return recent.length > RATE_LIMIT_MAX_REQUESTS
}

function cosineSimilarity(a, b) {
  let dot = 0
  let normA = 0
  let normB = 0
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i]
    normA += a[i] * a[i]
    normB += b[i] * b[i]
  }
  return dot / (Math.sqrt(normA) * Math.sqrt(normB))
}

function topChunks(questionEmbedding, k) {
  return knowledgeBase
    .map((chunk) => ({ chunk, score: cosineSimilarity(questionEmbedding, chunk.embedding) }))
    .sort((a, b) => b.score - a.score)
    .slice(0, k)
    .map(({ chunk }) => chunk)
}

// Every chunk in the knowledge base is about Chandra, so his name carries no
// retrieval signal — but it does carry weight. Measured scores showed queries
// naming him pulling chunks that merely repeat the name ("Chandra
// hypothesized...") over genuinely on-topic ones that never spell it out
// ("A story-first gamer..."), across a corpus whose entire similarity range
// is only ~0.15 wide. Stripping the name from the *query embedding input*
// removes that bias. Whole-word only, so "Chandrashekhar" is left alone; the
// optional possessive avoids leaving a dangling "'s". The generation model
// still receives the original, unedited question.
const NAME_PATTERN = /\b(?:chandramouli|chandra)(?:['’]s)?\b/gi

function stripNameForEmbedding(text) {
  const stripped = text.replace(NAME_PATTERN, ' ').replace(/\s+/g, ' ').trim()
  // A question that is nothing but the name would strip to empty; embedding
  // an empty string errors, so fall back to the original text.
  return stripped.length > 0 ? stripped : text
}

// Retry + timeout protection for the embed/generate round trip. Added
// after Gemini's flash tier returned transient 503s where a single
// failing attempt could itself hang ~10-13s before the SDK surfaced the
// error. Generation has since moved to Groq, but the embedding call is
// still Gemini and still carries that risk, so this stays. The explicit
// timeout is deliberate rather than relying on an SDK's own timeout
// option (Gemini's httpOptions.timeout is known-broken in this version
// per googleapis/js-genai#1277). Worst case: 2 * 7s + 1 * 0.5s ≈ 14.5s,
// comfortably inside the 20s maxDuration above.
const MAX_ATTEMPTS = 2
const ATTEMPT_TIMEOUT_MS = 7000
const RETRY_DELAY_MS = 500

function withTimeout(promise, ms) {
  return Promise.race([
    promise,
    new Promise((_, reject) => {
      setTimeout(() => reject(new Error(`Attempt timed out after ${ms}ms`)), ms)
    }),
  ])
}

async function withRetry(fn) {
  let lastError
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {
      return await withTimeout(fn(), ATTEMPT_TIMEOUT_MS)
    } catch (error) {
      lastError = error
      if (attempt < MAX_ATTEMPTS) {
        console.error(`Attempt ${attempt} failed, retrying:`, error.message)
        await new Promise((resolve) => setTimeout(resolve, RETRY_DELAY_MS))
      }
    }
  }
  throw lastError
}

export default async function handler(request, response) {
  if (request.method !== 'POST') {
    response.status(405).json({ error: 'Method not allowed. Use POST.' })
    return
  }

  const ip = getClientIp(request)
  if (isRateLimited(ip)) {
    response.status(429).json({ error: 'Too many requests. Please wait a moment and try again.' })
    return
  }

  const geminiApiKey = process.env.GEMINI_API_KEY
  const groqApiKey = process.env.GROQ_API_KEY
  if (!geminiApiKey || !groqApiKey) {
    console.error(
      `Missing API key(s) in the function environment: ${
        [!geminiApiKey && 'GEMINI_API_KEY', !groqApiKey && 'GROQ_API_KEY'].filter(Boolean).join(', ')
      }`,
    )
    response.status(500).json({ error: 'Server is not configured correctly.' })
    return
  }

  let body
  try {
    body = request.body
  } catch {
    response.status(400).json({ error: 'Malformed request body.' })
    return
  }

  const question = typeof body?.question === 'string' ? body.question.trim() : ''

  if (question.length === 0) {
    response.status(400).json({ error: 'Question is required.' })
    return
  }

  if (question.length > MAX_QUESTION_LENGTH) {
    response
      .status(400)
      .json({ error: `Question must be ${MAX_QUESTION_LENGTH} characters or fewer.` })
    return
  }

  const ai = new GoogleGenAI({ apiKey: geminiApiKey })
  const groq = new Groq({ apiKey: groqApiKey })

  try {
    const { answer, sources } = await withRetry(async () => {
      const embedQuery = stripNameForEmbedding(question)
      const embedResponse = await ai.models.embedContent({
        model: EMBEDDING_MODEL,
        contents: embedQuery,
        config: { taskType: 'RETRIEVAL_QUERY' },
      })
      const questionEmbedding = embedResponse.embeddings[0].values

      const relevantChunks = topChunks(questionEmbedding, TOP_K)
      const contextBlock = relevantChunks
        .map((chunk) => `### ${chunk.heading}\n${chunk.text}`)
        .join('\n\n')

      const completion = await groq.chat.completions.create({
        model: GENERATION_MODEL,
        messages: [
          { role: 'system', content: SYSTEM_INSTRUCTION },
          { role: 'user', content: `Context:\n${contextBlock}\n\nQuestion: ${question}` },
        ],
      })

      // gpt-oss is a reasoning model, but on Groq the chain-of-thought is
      // returned separately in message.reasoning — message.content is the
      // final answer only, so nothing internal leaks into the chat.
      const generatedAnswer = completion.choices[0]?.message?.content?.trim()
      if (!generatedAnswer) {
        throw new Error('Empty response from generation model.')
      }

      const dedupedSources = [...new Set(relevantChunks.map((chunk) => chunk.heading))].map(
        (heading) => ({ heading }),
      )

      return { answer: generatedAnswer, sources: dedupedSources }
    })

    response.status(200).json({ answer, sources })
  } catch (error) {
    console.error('Ask Anything request failed after retry:', error.message)
    response.status(502).json({
      error: 'Something went wrong answering that question. Please try again.',
    })
  }
}
